import type { ProjetGalerieTableauDeBord } from "@/types/dashboard.types";

export const MOCK_PROJECTS: ProjetGalerieTableauDeBord[] = [
  {
    identifiant: "PRJ-001",
    titre: "Installation Vidéoprotection VIP",
    categorie: "Sécurité",
    client: "Villa Horizon",
    localisation: "Douala, Bonapriso",
    date: "2026-04-15",
    progression: 100,
    statut: "completed",
    image: "/images/Group 24.png",
    resume: "Déploiement complet de 16 caméras IP 4K avec vision nocturne et IA de reconnaissance faciale pour une résidence de haut standing.",
  },
  {
    identifiant: "PRJ-002",
    titre: "Câblage Fibre Optique",
    categorie: "Réseaux",
    client: "Immeuble Central",
    localisation: "Yaoundé, Akwa",
    date: "2026-05-02",
    progression: 65,
    statut: "actif",
    image: "/images/Group 25.png",
    resume: "Raccordement en fibre optique de bout en bout pour un immeuble de bureaux de 10 étages. Configuration des répartiteurs principaux.",
  },
  {
    identifiant: "PRJ-003",
    titre: "Système Solaire Autonome",
    categorie: "Énergie",
    client: "Hôtel Azur",
    localisation: "Kribi",
    date: "2026-05-10",
    progression: 25,
    statut: "actif",
    image: "/images/Group 26.png",
    resume: "Installation de 50 panneaux solaires et batteries au lithium pour garantir une autonomie énergétique à l'hôtel.",
  },
  {
    identifiant: "PRJ-004",
    titre: "Domotique Résidentielle",
    categorie: "Domotique",
    client: "Résidence Les Palmiers",
    localisation: "Yaoundé, Bastos",
    date: "2026-05-14",
    progression: 0,
    statut: "pending_validation",
    image: "/images/image-choix.png",
    resume: "Automatisation de l'éclairage, climatisation et sécurité via une interface centralisée sur tablette et smartphone.",
  }
];
